authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name="login"),
    path('logout/', authapp.logout, name="logout"),
    path('register/', authapp.register, name='register'),
    #path('edit/', authapp.edit, name='edit')
]

playbooks/urls.py
from django.contrib import admin
from django.urls import path, include
import playbooks.views as playbook

app_name = 'playbooks'
urlpatterns = [
    path('', playbook.PlaybookListView.as_view(), name='book'),
    path('playbook_add/', playbook.PlaybookCreateView.as_view(), name='playbook_add'),
    #path('playbook_add/', playbook.playbook, name='playbook_add')
]

testldap/urls.py
from django.contrib import admin
from django.urls import path, include
import authapp.views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authapp.urls', namespace='auth')),
    path('', auth.main, name="index"),
    path('playbooks/', include('playbooks.urls', namespace='playbooks'))
]

authapp/models.py
from django.db import models

# Create your models here.

playbooks/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
# Create your models here.

class Playbook(models.Model):
    name = models.CharField(max_length=100)
    image_product = models.ImageField(upload_to="image_product", blank=True, validators =[FileExtensionValidator(allowed_extensions=['jpg'])])
    create_at = models.DateTimeField(auto_now_add=True)

authapp/forms.py
from django.contrib.auth.forms import (AuthenticationForm,
                                       UserCreationForm,
                                       UserChangeForm, forms)
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

class UserForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.error_messages['required'] = ''
            field.widget.attrs['class'] = 'form-control'

bootstrap_modal_forms/forms.py
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


class BSModalForm(PopRequestMixin, forms.Form):
    pass


class BSModalModelForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    pass

playbooks/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from bootstrap_modal_forms.forms import BSModalModelForm, BSModalForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from .models import Playbook
import os



class PlaybookForm(BSModalModelForm):
    # def clean_file(self):
    #     file = self.cleaned_data.get("playbook", False)
    #     filetype = magic.from_buffer(file.read())
    #     if not "XML" in filetype:
    #         raise ValidationError("File is not XML.")
    #     return file

    class Meta:
        model = Playbook
        exclude = ('create_at',)

authapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import auth
from django.urls import reverse
from authapp.forms import *
from .ldapauth import main as ldaptest
import testldap.settings as set
from django_auth_ldap.backend import LDAPBackend

def login(request):
    login_form = UserForm(data=request.POST)
    username = request.POST['username']
    password = request.POST['password']
    print(username)
    print(password)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        print(username)
        print(password)
        #auth = LDAPBackend()

        user = auth.authenticate(request, username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))

    content = {'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def register(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            user = register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = RegisterForm()

    content = {'register_form': register_form}
    return render(request, 'authapp/register.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))




def main(request):
    #y = ldaptest()
    #var = set.AUTH_LDAP_BIND_PASSWORD
    #print(var)
    #u = main1()
    #print(y)
    #print(u)
    return render(request, 'authapp/index.html')

playbooks/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic

from bootstrap_modal_forms.generic import (
    BSModalLoginView,
    BSModalFormView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalReadView,
    BSModalDeleteView
)

from .forms import (

    PlaybookForm
)
from .models import Playbook

def playbook_add(request):
    pass

def playbook(request):
    return render(request, 'playbooks/playbook_list.html')

class PlaybookCreateView(BSModalCreateView):
    template_name = 'examples/create_playbook.html'
    form_class = PlaybookForm

    success_message = 'Success: Book was created.'
    success_url = reverse_lazy('playbooks:book')

class PlaybookListView(generic.ListView):
    model = Playbook
    template_name = 'playbooks/playbooks_list.html'

    def get_ordering(self):
        return '-create_at'

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
   {% block head %}
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    {% endblock %}
</head>
<body>
    {% block content %}

    {% endblock %}

</body>
</html>

authapp/templates/authapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Контент
<a href="{% url 'playbooks:book' %}">dsadada</a>
    {{content}}
    {{content1}}
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}

    <div class="col-md-6 login-form-1">
                        <h3>Login</h3>
        <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
            {% csrf_token %}
            {{ login_form.as_p }}
            <br>
            <input class="form-control" type="submit" value="войти">

        </form>

        <a href="{% url 'auth:register' %}" class="link">
            <button class="form-control">
            Регистрация
            </button>
        </a>


        <a href="{% url 'index' %}" class="link">
            <button class="form-control">
            На главную
            </button>
        </a>

    </div>
{% endblock %}

authapp/templates/authapp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    fdfsmfmdsfl
</body>
</html>

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}

    <div class="col-md-6 login-form-1">
            <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ register_form.as_p }}
                <br>
                <input class="form-control" type="submit" value="Зарегистрироваться">
            </form>

        <a href="{% url 'index' %}" class="link">
            <button class="form-control">
            На главную
            </button>
        </a>

    </div>


{% endblock %}

playbooks/templates/examples/create_playbook.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Create Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Create</button>
  </div>

</form>

playbooks/templates/examples/delete_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Are you sure you want to delete book with title
      <strong>{{ book.title }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

playbooks/templates/examples/filter_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Filter Books</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>


  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>


  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Filter</button>
  </div>

</form>

playbooks/templates/examples/login.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Log in</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" formnovalidate="formnovalidate">Log in</button>
  </div>

</form>

playbooks/templates/examples/read_book.html
{% load widget_tweaks %}

<div class="modal-header">
  <h3 class="modal-title">Book details</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">

  <div class="">
    Title:
    {{ book.title }}
  </div>
  <div class="">
    Author:
    {{ book.author }}
  </div>
  <div class="">
    Price:
    {{ book.price }}
    €
  </div>
  <div class="">
    Pages:
    {{ book.pages }}
  </div>
  <div class="">
    Type:
    {{ book.get_book_type_display }}
  </div>
  <div class="">
    Publication date:
    {{ book.publication_date }}
  </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

playbooks/templates/examples/signup.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Sign up</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary" formnovalidate="formnovalidate">Sign up</button>
  </div>

</form>

playbooks/templates/examples/update_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Update</button>
  </div>

</form>

playbooks/templates/playbooks/111.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

playbooks/templates/playbooks/_header.html
{% load static %}

<!-- Header -->
<header style="border-bottom: 1px solid #eee;">
  <!-- Messages -->
  <div>
    {% if messages %}
      {% for message in messages %}
        <div style="border-radius:0;" {% if message.tags %} class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert" {% endif %}>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <!-- End Messages -->
  <div class="container">
    <!-- Navbar -->
    <!-- Important: columns can be used directly in navbar since it is d-flex -->
    <nav class="navbar navbar-expand-md navbar-light p-0 py-2">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <h1>
              <a class="nav-link p-0" href="/">django-bootstrap-modal-forms
                <span class="sr-only">(current)</span></a>
            </h1>
          </li>
        </ul>
        <p class="text-muted ml-auto m-0">Created and maintained by
          <a href="https://github.com/trco" target="_blank" style="text-decoration: none;">
            <svg style="margin-bottom: -3px; margin-right: 2px;" viewbox="0 0 64 64" width="16" height="16">
              <path
                stroke-width="0"
                fill="currentColor"
                d="M32 0 C14 0 0 14 0 32 0 53 19 62 22 62 24 62 24 61 24 60 L24 55 C17 57 14 53 13 50 13 50 13 49 11 47 10 46 6 44 10 44 13 44 15 48 15 48 18 52 22 51 24 50 24 48 26 46 26 46 18 45 12 42 12 31 12 27 13 24 15 22 15 22 13 18 15 13 15 13 20 13 24 17 27 15 37 15 40 17 44 13 49 13 49 13 51 20 49 22 49 22 51 24 52 27 52 31 52 42 45 45 38 46 39 47 40 49 40 52 L40 60 C40 61 40 62 42 62 45 62 64 53 64 32 64 14 50 0 32 0 Z"></path>
            </svg>
          </a>
          <a href="https://github.com/trco" target="_blank">trco</a>
        </p>
      </div>
    </nav>
    <!-- End Navbar -->
  </div>
</header>
<!-- End Header -->

playbooks/templates/playbooks/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

playbooks/templates/playbooks/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    {% block stylesheets %}
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <!-- Font awesome CSS -->
      <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
      <!-- Custom CSS -->
      <style media="screen">
        .invalid {
          color: #dc3545;
          font-size: 80%;
        }
        body {
          display: flex;
          flex-direction: column;
          min-height: 100vh;
        }
        .footer {
          margin: auto 0 0;
          height: 56px;
        }
      </style>
    {% endblock stylesheets %}

    <title>django-bootstrap-modal-forms</title>
  </head>

  <body>

    <!-- Includes -->


    {% block content %}{% endblock content %}

    <!-- Includes -->


    <!-- JavaScript -->
    {% block scripts %}
      <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'assets/js/popper.min.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!-- You can alternatively load the minified version -->
      <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% endblock scripts %}

    {% block extrascripts %}{% endblock extrascripts %}

  </body>

</html>

playbooks/templates/playbooks/playbook.html
{% extends 'playbooks/base.html' %}

{% block content %}

  {% include "playbooks/_modal.html" %}

<button id="add_book" class="btn btn-primary" type="button" name="button">add</button>

<button id="add_book1" class="btn btn-primary" type="button" name="button">add</button>



 {% endblock content %}

{% block extrascripts %}

 <script type="text/javascript">

      $(function () {

          // Create book synchronous
          function createBookSyncModalForm() {
            $("#add_book").modalForm({

                formURL: "{% url 'playbooks:playbook_add' %}",
                modalID: "#create-modal"
            });
          }
          createBookSyncModalForm();
        })
 </script>
{% endblock extrascripts %}

playbooks/templates/playbooks/playbook_list.html
{% extends 'playbooks/base.html' %}

{% block content %}

  {% include "playbooks/_modal.html" %}

<button id="add_book" class="btn btn-primary" type="button" name="button">add</button>

<button id="add_book1" class="btn btn-primary" type="button" name="button">add</button>

<table>
    rwe
                {% for object in object_list%}
                    <tr>
                        <td width="3%"><div class="custom-control custom-checkbox" style="transform: translateX(15%)"><input class="custom-control-input" type="checkbox" id="{{object.id}}" ><label for="{{object.id}}" class="custom-control-label" style="cursor: pointer"></label></div></td>

                        <td>{{object.name}}</td>
                        <td>{{object.create_at}}</td>
                        <td>{{object.description}}</td>
                    </tr>
                    {% endfor %}
</table>

 {% endblock content %}

{% block extrascripts %}

 <script type="text/javascript">

      $(function () {

          // Create book synchronous
          function createBookSyncModalForm() {
            $("#add_book").modalForm({

                formURL: "{% url 'playbooks:playbook_add' %}",
                modalID: "#create-modal"
            });
          }
          createBookSyncModalForm();
        })
 </script>
{% endblock extrascripts %}